### ISSUE TITLE
Documentation: getting started and install 

### ISSUE THREAD

**Issue by rozzilla** [madebyshape/svg-convert#11]
I think it'd more clear for newbie users to add the _instruction_ note to **make sure jQuery**, which is obviously required by Lightbox, **is also loaded** before running the command `$('.svg-convert').svgConvert();` :+1:

**Comment by bymayo** [comment]
@rozzilla I'll add this in to the docs 👍

**Comment by rozzilla** [comment]
Great! :+1:

**Comment by bymayo** [comment]
Added this in now @rozzilla 💯 I might adjusted the README file to make installation instructions a bit better, but your merge request is fine for now 👍 Thanks for that.

**Comment by rozzilla** [comment]
You're welcome! This plugin is very useful for me :1st_place_medal:

**Comment by bymayo** [comment]
Great to hear @rozzilla :)
