### ISSUE TITLE
Chrome  50.0.2661.75

### ISSUE THREAD

**Issue by Phil2017** [madebyshape/svg-convert#3]
After updating to Chrome 50.0.2661.75 all images with the class "svg-convert" have become invisible. Same on Mac and PC.

**Comment by Phil2017** [comment]
Sorry... I was too fast with this. On some of my projects it's still working fine. I'm closing this for now since I don't have enough information.

**Comment by madebyshape** [comment]
Double check that when the SVG's are converted that they are given a height / width by your CSS. I normally do this by placing a tag around it... e.g...

`<i class="icon"><img src="icon.svg" alt="Icon" class="svg-convert"></i>`

**Comment by Phil2017** [comment]
Thank you... in fact when i do this:

`svg { width: 100%; height: 100%; }`

it works just fine... Looks like Chrome is demanding the size now

**Comment by madebyshape** [comment]
Strange! I did notice that Safari on iOS does require a size property to be defined

Glad you sorted it though :)
