### ISSUE TITLE
Not compatible in chrome

### ISSUE THREAD

**Issue by rosh8111** [madebyshape/svg-convert#4]
Hi, your code working prefect in Firefox, but in chrome, all my svg are not showing at all, even your demo file colors are not taken by your code.

Please can you provide a fix for this, really appreciate.

**Comment by madebyshape** [comment]
SVG's in Chrome either need a height or width set to make them show. 

See this other Closed issue: https://github.com/madebyshape/shape-svg-convert/issues/3

**Comment by madebyshape** [comment]
You could also edit the 'cleanUp' option on the plugin (See the docs) to make the script not remove the width and height if you don't want to add it yourself.

**Comment by rosh8111** [comment]
Sorry, my bad, i forgot add svg,img   width and height to 100%, once i add
it all good.

On Sat, Apr 30, 2016 at 5:27 PM, Shape notifications@github.com wrote:

> You could also edit the 'cleanUp' option on the plugin (See the docs) to
> make the script not remove the width and height if you don't want to add it
> yourself.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/madebyshape/shape-svg-convert/issues/4#issuecomment-215970018

## 

Thank you

Graphic Designer &
Pro Wordpress Theme Developer

T : +965 66970953 - E : roshan@imcsl.com
W: roshan-dpt.com

**Comment by madebyshape** [comment]
👍 
I'll make a note of this on the documentation as a few people keep missing this! :)
