### ISSUE TITLE
XML Parsing Error: not well-formed Location:  Line Number 1, Column 153:

### ISSUE THREAD

**Issue by umairrazzaq** [madebyshape/svg-convert#6]
Hi, first of all things for this amazing plugin. I've tried it and it works well, although I'm getting this js error in console. I've 6 svg images to convert so the errors shows 6 times. Can you please assist me how to fix this?

**Comment by umairrazzaq** [comment]
I kinda already have js script that does the same but it sends the same js error too. Here is the code;

`$('img.img-svg').each(function() {
        var $img = $(this);
        var imgID = $img.attr('id');
        var imgClass = $img.attr('class');
        var imgURL = $img.attr('src');

```
    $.get(imgURL, function(data) {
        // Get the SVG tag, ignore the rest
        var $svg = $(data).find('svg');

        // Add replaced image's ID to the new SVG
        if(typeof imgID !== 'undefined') {
            $svg = $svg.attr('id', imgID);
        }
        // Add replaced image's classes to the new SVG
        if(typeof imgClass !== 'undefined') {
            $svg = $svg.attr('class', imgClass+' replaced-svg');
        }

        // Remove any invalid XML tags as per http://validator.w3.org
        $svg = $svg.removeAttr('xmlns:a');

        // Check if the viewport is set, else we gonna set it if we can.
        if(!$svg.attr('viewBox') && $svg.attr('height') && $svg.attr('width')) {
            $svg.attr('viewBox', '0 0 ' + $svg.attr('height') + ' ' + $svg.attr('width'))
        }

        // Replace image with new SVG
        $img.replaceWith($svg);

    }, 'xml');

});`
```

**Comment by madebyshape** [comment]
Are you running this on a server environment, and not locally? Theres issues with converting `.svg` to `<svg>` when not running on a server. You get Cross Origin and XML errors.

I'd also check the SVG that your converting, as this could be causing the error. Clean up the SVG using SVGOMG (https://jakearchibald.github.io/svgomg) and see if this helps.

**Comment by umairrazzaq** [comment]
I'm using it on static html template on windows.

**Comment by madebyshape** [comment]
That might be the issue. Try running those files on a server, localhost or through something like MAMP. I suspect the problem is it can't get the raw data from the file.

**Comment by madebyshape** [comment]
I just also Googled your error and it seems like it could be an issue with the SVG itself. Did you try optimising the SVG with SVGOMG?

**Comment by umairrazzaq** [comment]
Hi, Thanks MadebyShape for the reply and apologize about late replying, as i never got a chance to open github, also i didn't get any email notification for this - strange.

Anyways, turns out the SVG does working fine, but it will show error if runs in static html document.

**Comment by madebyshape** [comment]
No problem - Yeah you can't run SVG Convert on a static HTML doc, it needs to be run on a server to get over the Cross Origin / XML issues.

Glad you sorted it :)
