### ISSUE TITLE
Overwrite the class style

### ISSUE THREAD

**Issue by ipetrov87** [madebyshape/svg-convert#7]
Hi!

I have a several images that are converted in SVGs. The problem is that all SVG have a **path** tag with class **cls-1**. First SVG have this styling for that class
`fill: #ef7c00;`
Then i have this class overwriten from next five SVGs like this 

```
fill: none;
stroke: #575757;
stroke-miterlimit: 10;
stroke-width: 1.05px;
```

The problem is that this way it is changed filled color for my first SVG and do not want that. My first SVG is styled like the last that is converted.

**Comment by madebyshape** [comment]
Do you mean you don't want the first SVG that is converted to have the class that overwrites the fill? 

If not, could you provide an example on Codepen or something?

**Comment by ipetrov87** [comment]
Here is the [link](http://codepen.io/ipetrov/pen/ZpxwAz). Fisrt N need to be orange with no border.

**Comment by madebyshape** [comment]
The plugin only really offers a way of converting the images from `.svg`, to `<svg>` - I don't really offer support regarding the styling of your SVG's. But as an exception, try something like:

```
#headerLogo path {
  fill: orange;
  stroke: transparent
}
```

**Comment by ipetrov87** [comment]
I am sure that this will help to fix my issue, i think if there is a way to set that the styled define in the SVG in visible by only that SVG and not all other the this need to be done and will fix the issue. Just make this style to be local for the SVG that that define them. Is this possible?

**Comment by madebyshape** [comment]
If the SVG has styling in side of the file itself then it will pull through that styling. I'd personally say that SVG code is pretty messy.  I'd suggest running it through SVG OMG https://jakearchibald.github.io/svgomg/

**Comment by ipetrov87** [comment]
Same result.

**Comment by madebyshape** [comment]
Closing this issue as it's a styling bug on your side, not anything to do with the SVG being converted.
