### ISSUE TITLE
Bower

### ISSUE THREAD

**Issue by simoneprodesign** [madebyshape/svg-convert#8]
Please, update ur bower package.

With the svg-convert this is not found.

Thanks!

**Comment by madebyshape** [comment]
Whoops! Sorry, will sort this out. My mistake as I changed the name of the plugin.

**Comment by madebyshape** [comment]
Updated the Bower version and registered it to Bower! Should be sorted. Thanks for letting me know.

**Comment by simoneprodesign** [comment]
Thanks for ur reply. I've try to install the new package but doesnt'work. I wrote the command in the terminal (bower uninstall shape-svg-convert and bower install svg-convert) and then i have a same package.

**Comment by madebyshape** [comment]
Okay, i'll try this out in Bower, I just registered it again. Will run a test when installing it shortly.

**Comment by simoneprodesign** [comment]
Thanks, i will try soon

**Comment by simoneprodesign** [comment]
Nope, doesn't work.
